"""AI Response Security Scanner.
Component 30.12: Scans completions for leaked secrets, sensitive data exfiltration, and dangerous commands.
"""
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from enum import Enum
import re
import time


class ResponseRiskType(str, Enum):
    SECRET_LEAK = "SECRET_LEAK"
    PII_EXPOSURE = "PII_EXPOSURE"
    UNSAFE_COMMAND = "UNSAFE_COMMAND"
    PROPRIETARY_CODE_LEAK = "PROPRIETARY_CODE_LEAK"


@dataclass
class ResponseScanFinding:
    risk_type: ResponseRiskType
    severity: str
    description: str
    matched_snippet: str
    remediation: str


class ResponseSecurityScanner:
    """Scans raw completions generated by LLMs before passing them to the caller or tools."""

    SECRET_REGEX = [
        re.compile(r"(?:api[_-]?key|token|password|secret)\s*[:=]\s*['\"]?[a-zA-Z0-9_\-\.]{16,}['\"]?", re.IGNORECASE),
        re.compile(r"-----BEGIN (?:RSA |EC )?PRIVATE KEY-----"),
        re.compile(r"AKIA[0-9A-Z]{16}"),
    ]

    UNSAFE_SHELL_REGEX = [
        re.compile(r"(?:rm\s+-rf|chmod\s+777|chown\s+root|mkfs|dd\s+if=)"),
        re.compile(r"(?:nc\s+-[e|c]|bash\s+-i|/bin/sh\s+-i)"),
        re.compile(r"(?:curl|wget)\s+http[s]?://[a-zA-Z0-9\.\-]+/\S+\s*\|\s*(?:bash|sh)"),
    ]

    def scan_response(self, text: str) -> List[ResponseScanFinding]:
        findings: List[ResponseScanFinding] = []

        # 1. Secret leaks
        for p in self.SECRET_REGEX:
            m = p.search(text)
            if m:
                findings.append(
                    ResponseScanFinding(
                        risk_type=ResponseRiskType.SECRET_LEAK,
                        severity="CRITICAL",
                        description="Model completion contains raw API key or cryptographic private key.",
                        matched_snippet=m.group(0)[:32] + "...",
                        remediation="Block output release and rotate exposed credential immediately.",
                    )
                )

        # 2. Unsafe shell commands
        for p in self.UNSAFE_SHELL_REGEX:
            m = p.search(text)
            if m:
                findings.append(
                    ResponseScanFinding(
                        risk_type=ResponseRiskType.UNSAFE_COMMAND,
                        severity="HIGH",
                        description="Model generated dangerous destructive or reverse shell command.",
                        matched_snippet=m.group(0),
                        remediation="Prevent command execution by agent tool layer.",
                    )
                )

        return findings
