from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class LLMProvider(Protocol):
    def generate(self, messages: List[Dict[str, str]], tools: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
        ...


class MockProvider:
    def generate(self, messages: List[Dict[str, str]], tools: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
        return {"content": "Structured evidence-based investigation summary generated by mock provider."}


class LocalLLMProvider(MockProvider):
    pass


class OpenAICompatibleProvider(MockProvider):
    pass


class EnterpriseProvider(MockProvider):
    pass


__all__ = ["LLMProvider", "MockProvider", "LocalLLMProvider", "OpenAICompatibleProvider", "EnterpriseProvider"]
