import json
import uuid
import time
import logging
import argparse
from datetime import datetime, timezone
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Any, Optional, Set

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] Phase15 - %(message)s")
logger = logging.getLogger("Agentic-Copilot")

try:
    from fastapi import FastAPI, HTTPException, BackgroundTasks, Depends
    import uvicorn
    HAS_FASTAPI = True
except ImportError:
    HAS_FASTAPI = False
    logger.warning("FastAPI not installed. Copilot API mode disabled.")

@dataclass
class AgentTool:
    """Defines a capability available to the AI, protected by a strict Level (L0-L4)."""
    name: str
    level: int # 0=READ, 1=ANALYZE, 2=WRITE_CASE, 3=LOW_IMPACT_ACTION, 4=HIGH_IMPACT_ACTION
    description: str
    requires_approval: bool = False

@dataclass
class EvidenceObservation:
    """A grounded fact retrieved by the Evidence Agent."""
    evidence_id: str
    source_type: str
    observation: str
    confidence: float
    is_inferred: bool = False

@dataclass
class Hypothesis:
    """A structured hypothesis generated by the Investigation Agent."""
    hypothesis_id: str
    statement: str
    supporting_evidence: List[str] = field(default_factory=list)
    contradicting_evidence: List[str] = field(default_factory=list)
    missing_evidence: List[str] = field(default_factory=list)
    confidence: float = 0.0
    status: str = "UNDER_REVIEW" # UNDER_REVIEW, SUPPORTED, UNSUPPORTED

@dataclass
class InvestigationStep:
    step_id: int
    tool: str
    arguments: Dict[str, Any]
    status: str = "PENDING"
    result: Optional[str] = None

@dataclass
class ActionProposal:
    action_id: str
    tool_name: str
    target: str
    justification: str
    requires_approval: bool
    status: str = "PROPOSED" # PROPOSED, APPROVED, REJECTED, EXECUTED, VERIFIED

@dataclass
class AgentRun:
    """The master state machine object for an autonomous investigation."""
    run_id: str
    case_id: str
    status: str = "NEW" # NEW, PLANNING, EVIDENCE_COLLECTION, HYPOTHESIS_EVALUATION, RESPONSE_PLANNING, PENDING_APPROVAL, VERIFIED, CLOSED
    objective: str = ""
    steps: List[InvestigationStep] = field(default_factory=list)
    evidence: List[EvidenceObservation] = field(default_factory=list)
    hypotheses: List[Hypothesis] = field(default_factory=list)
    actions: List[ActionProposal] = field(default_factory=list)
    audit_trail: List[Dict[str, Any]] = field(default_factory=list)

class GuardrailEngine:
    """Ensures the Agent cannot exceed its permissions or hallucinate actions."""
    def __init__(self):
        self.tools = {
            "get_certificate": AgentTool("get_certificate", 0, "Retrieve certificate history"),
            "query_knowledge_graph": AgentTool("query_knowledge_graph", 0, "Query asset relationships"),
            "search_historical_baseline": AgentTool("search_historical_baseline", 1, "Compare with baseline"),
            "create_hypothesis": AgentTool("create_hypothesis", 2, "Write hypothesis to case"),
            "create_ticket": AgentTool("create_ticket", 3, "Create an IT ticket"),
            "update_tls_policy": AgentTool("update_tls_policy", 4, "Modify infrastructure TLS policy", requires_approval=True),
            "block_indicator": AgentTool("block_indicator", 4, "Block an IP/Domain", requires_approval=True)
        }

    def validate_tool_call(self, tool_name: str, requested_level: int) -> AgentTool:
        tool = self.tools.get(tool_name)
        if not tool:
            raise ValueError(f"Tool {tool_name} is not registered or allowed.")
        if tool.level > requested_level:
            raise PermissionError(f"Agent lacks permission for L{tool.level} tool: {tool_name}")
        return tool

class EvidenceAgent:
    """Responsible for retrieving L0/L1 facts and guaranteeing groundedness."""
    def __init__(self, guardrails: GuardrailEngine):
        self.guardrails = guardrails

    def retrieve_context(self, case_id: str, query: str) -> List[EvidenceObservation]:
        """Mocks retrieving grounded evidence from Phase 14's Knowledge Graph."""
        logger.info(f"[EvidenceAgent] Retrieving context for '{query}'...")
        self.guardrails.validate_tool_call("query_knowledge_graph", 0)
        
        # Mocks retrieving deterministic observations
        return [
            EvidenceObservation(f"EV-{uuid.uuid4().hex[:4]}", "PCAP", "TLS 1.1 negotiated on 38 sessions.", 1.0),
            EvidenceObservation(f"EV-{uuid.uuid4().hex[:4]}", "GRAPH", "JA4-X was first seen 24 hours ago.", 1.0),
            EvidenceObservation(f"EV-{uuid.uuid4().hex[:4]}", "BASELINE", "Asset MTA-04 historically uses TLS 1.3.", 0.95)
        ]

class InvestigationAgent:
    """Reasons over evidence to formulate investigation plans and hypotheses."""
    def build_plan(self, objective: str) -> List[InvestigationStep]:
        logger.info("[InvestigationAgent] Building investigation plan...")
        return [
            InvestigationStep(1, "query_knowledge_graph", {"query": "Find associated assets for JA4-X"}),
            InvestigationStep(2, "search_historical_baseline", {"asset": "MTA-04"}),
            InvestigationStep(3, "create_hypothesis", {"action": "synthesize"})
        ]

    def generate_hypotheses(self, evidence: List[EvidenceObservation]) -> List[Hypothesis]:
        logger.info("[InvestigationAgent] Generating competing hypotheses based on evidence...")
        # Simulate LLM reasoning
        h1 = Hypothesis(
            hypothesis_id="H1",
            statement="Configuration downgrade on MTA-04.",
            supporting_evidence=[e.evidence_id for e in evidence if "MTA-04" in e.observation],
            missing_evidence=["Change management ticket confirmation"],
            confidence=0.85
        )
        h2 = Hypothesis(
            hypothesis_id="H2",
            statement="Legacy client behavior.",
            supporting_evidence=[e.evidence_id for e in evidence if "JA4" in e.observation],
            contradicting_evidence=[e.evidence_id for e in evidence if "TLS 1.1" in e.observation],
            confidence=0.30
        )
        return [h1, h2]

class ResponsePlanner:
    """Translates conclusions into actionable response proposals."""
    def __init__(self, guardrails: GuardrailEngine):
        self.guardrails = guardrails

    def propose_actions(self, hypothesis: Hypothesis) -> List[ActionProposal]:
        logger.info(f"[ResponsePlanner] Proposing response for Hypothesis {hypothesis.hypothesis_id}")
        
        actions = []
        # Simulate LLM action generation
        if hypothesis.confidence > 0.8:
            tool = self.guardrails.tools["update_tls_policy"]
            actions.append(ActionProposal(
                action_id=f"ACT-{uuid.uuid4().hex[:6].upper()}",
                tool_name=tool.name,
                target="MTA-04",
                justification=f"Disable TLS 1.1 to mitigate {hypothesis.statement}",
                requires_approval=tool.requires_approval
            ))
        return actions

class AgentOrchestrator:
    """Controls the lifecycle and state transitions of the autonomous investigation."""
    def __init__(self):
        self.guardrails = GuardrailEngine()
        self.evidence_agent = EvidenceAgent(self.guardrails)
        self.investigation_agent = InvestigationAgent()
        self.response_planner = ResponsePlanner(self.guardrails)
        self.runs: Dict[str, AgentRun] = {}

    def start_investigation(self, case_id: str, objective: str) -> AgentRun:
        run_id = f"AG-{uuid.uuid4().hex[:8].upper()}"
        run = AgentRun(run_id=run_id, case_id=case_id, objective=objective)
        self.runs[run_id] = run
        self._audit(run, "Agent started investigation.")
        
        # State: PLANNING
        run.status = "PLANNING"
        run.steps = self.investigation_agent.build_plan(objective)
        self._audit(run, f"Generated {len(run.steps)} step investigation plan.")
        
        return run

    def execute_next_phase(self, run_id: str):
        """Advances the state machine of the agent."""
        run = self.runs.get(run_id)
        if not run:
            return

        if run.status == "PLANNING":
            run.status = "EVIDENCE_COLLECTION"
            run.evidence = self.evidence_agent.retrieve_context(run.case_id, run.objective)
            self._audit(run, f"Collected {len(run.evidence)} grounded evidence artifacts.")
            
        elif run.status == "EVIDENCE_COLLECTION":
            run.status = "HYPOTHESIS_EVALUATION"
            run.hypotheses = self.investigation_agent.generate_hypotheses(run.evidence)
            self._audit(run, f"Generated {len(run.hypotheses)} competing hypotheses.")
            
        elif run.status == "HYPOTHESIS_EVALUATION":
            run.status = "RESPONSE_PLANNING"
            best_hypothesis = max(run.hypotheses, key=lambda h: h.confidence)
            run.actions = self.response_planner.propose_actions(best_hypothesis)
            
            requires_human = any(a.requires_approval for a in run.actions)
            run.status = "PENDING_APPROVAL" if requires_human else "VERIFIED"
            self._audit(run, f"Proposed {len(run.actions)} actions. Status -> {run.status}")

    def _audit(self, run: AgentRun, message: str):
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "message": message,
            "status": run.status
        }
        run.audit_trail.append(entry)
        logger.info(f"[{run.run_id}] {message}")

    def approve_action(self, run_id: str, action_id: str, user: str):
        run = self.runs.get(run_id)
        if not run:
            raise ValueError("Run not found")
            
        for action in run.actions:
            if action.action_id == action_id and action.status == "PROPOSED":
                action.status = "APPROVED"
                self._audit(run, f"Action {action_id} APPROVED by {user}.")
                
                # Mock execution and verification
                action.status = "EXECUTED"
                self._audit(run, f"Action {action_id} EXECUTED.")
                
                # Assume the verification agent runs and confirms the fix
                run.status = "VERIFIED"
                self._audit(run, f"Verification Agent confirmed remediation. Case closed.")
                return action
        raise ValueError("Action not found or not in PROPOSED state.")

if HAS_FASTAPI:
    app = FastAPI(title="Phase 15 - Forensic Copilot API")
    orchestrator = AgentOrchestrator()

    @app.post("/api/v1/agents/investigate", tags=["Copilot"])
    def start_investigation(case_id: str, objective: str):
        """Starts an autonomous agentic investigation on a given case."""
        run = orchestrator.start_investigation(case_id, objective)
        # Auto-advance for API convenience
        orchestrator.execute_next_phase(run.run_id) # Evidence
        orchestrator.execute_next_phase(run.run_id) # Hypothesis
        orchestrator.execute_next_phase(run.run_id) # Response
        return asdict(run)

    @app.get("/api/v1/agents/runs/{run_id}", tags=["Copilot"])
    def get_run_status(run_id: str):
        run = orchestrator.runs.get(run_id)
        if not run:
            raise HTTPException(404, "Run not found")
        return asdict(run)

    @app.post("/api/v1/actions/{action_id}/approve", tags=["Governance"])
    def approve_action(action_id: str, run_id: str, user: str = "SOC_Admin"):
        """Human-in-the-loop approval gateway for high-impact actions."""
        try:
            action = orchestrator.approve_action(run_id, action_id, user)
            return {"status": "success", "action": asdict(action)}
        except ValueError as e:
            raise HTTPException(400, str(e))

def run_phase15_demo():
    print("\n" + "="*70)
    print(" PHASE 15: AGENTIC FORENSIC COPILOT & AUTONOMOUS INVESTIGATION")
    print("="*70 + "\n")
    
    orchestrator = AgentOrchestrator()
    case_id = "CASE-2026-991"
    objective = "Investigate TLS 1.1 fallback anomaly associated with JA4-X on MTA-04"
    
    # 1. Orchestrator Initialization & Planning
    print(f"[*] USER: '{objective}'")
    run = orchestrator.start_investigation(case_id, objective)
    print(f"\n[COPILOT] Created Plan (Run ID: {run.run_id}):")
    for step in run.steps:
        print(f"   -> Step {step.step_id}: {step.tool} ({step.arguments})")
        
    time.sleep(1)
    
    # 2. Evidence Collection
    print("\n[*] ORCHESTRATOR: Advancing to EVIDENCE_COLLECTION...")
    orchestrator.execute_next_phase(run.run_id)
    print("[EVIDENCE AGENT] Retrieved Grounded Observations:")
    for ev in run.evidence:
        print(f"   -> [Conf: {ev.confidence:.2f}] {ev.observation}")

    time.sleep(1)

    # 3. Hypothesis Generation
    print("\n[*] ORCHESTRATOR: Advancing to HYPOTHESIS_EVALUATION...")
    orchestrator.execute_next_phase(run.run_id)
    print("[INVESTIGATION AGENT] Competing Hypotheses Generated:")
    for h in run.hypotheses:
        print(f"   -> {h.hypothesis_id} [{h.confidence*100:.0f}%]: {h.statement}")
        print(f"      Missing Evidence: {h.missing_evidence}")

    time.sleep(1)

    # 4. Response Planning & Approval Gate
    print("\n[*] ORCHESTRATOR: Advancing to RESPONSE_PLANNING...")
    orchestrator.execute_next_phase(run.run_id)
    
    print("\n[APPROVAL GATEWAY] The Agent has proposed actions requiring human approval:")
    for action in run.actions:
        print(f"   -> ID: {action.action_id} | Tool: {action.tool_name} | Target: {action.target}")
        print(f"      Justification: {action.justification}")
        print(f"      Status: {action.status}")
        
    # 5. Human Execution and Verification
    if run.actions:
        action_id = run.actions[0].action_id
        print(f"\n[*] HUMAN ANALYST: Approving action {action_id}...")
        orchestrator.approve_action(run.run_id, action_id, "Alice (Senior DFIR)")
        
    print("\n[VERIFICATION AGENT] Monitoring telemetry... TLS 1.1 no longer observed on MTA-04. Remediation VERIFIED.")
    print(f"\n[✓] Phase 15 Complete. Final Run Status: {run.status}")

def main():
    parser = argparse.ArgumentParser(description="Phase 15 - Agentic Forensic Copilot")
    parser.add_argument("command", choices=["serve", "demo"], help="Command to run", default="demo", nargs="?")
    args = parser.parse_args()

    if args.command == "serve":
        if HAS_FASTAPI:
            print("Starting Phase 15 Copilot API on port 8000...")
            uvicorn.run(app, host="127.0.0.1", port=8000)
        else:
            print("FastAPI not installed. Run 'demo' instead.")
    elif args.command == "demo":
        run_phase15_demo()

if __name__ == "__main__":
    main()